fos_ck_editor:
  configs:
    my_config:
      toolbar: [ [ "Source", "-", "Save" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
      uiColor: "#123456"
      filebrowserUploadRoute: "my_route"
      extraPlugins: "wordcount"